[package]
name = "rust-movies"
version = "0.1.0"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]

[dependencies]
postgres = { version = "0.15", features = ["with-chrono"] }
chrono = "0.4"
iron = "0.5.*"